### ISSUE TITLE
Website revamp - proposed structure and TODO list

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/PredictiveEcology.org#2]
The PredictiveEcology.org website is undergoing changes focused on centralising and integrating information about PERFICT, SpaDES, SpaDES modules, SpaDES training, as well as existing PERFICT and SpaDES-based projects, all of which are currently more or less scattered across multiple web-locations.
Part of this change also involves shifting from a "lab-website" structure to a "PERFICT Community website" structure.

The proposed new structure is as follows. The highest heading level inticates a tab on the horizontal navigation bar and subheadings  indicate pages nested in each tab (appearing as drop down menu). A few specific tasks have been associated with the each heading/subheading, but see also the TODO list below.

# **New website structure**

## PERFICT 
The landing page with a brief introduction about PERFICT and how we've been implementing it in this community

### About
More detailed information about PERFICT concepts and workflows with links to other relevant "internal" (i.e. this website) and external pages.

### Projects
A list of projects based on PERFICT principles with links to project pages/manuals (e.g. LandWeb) where they exist.

```[tasklist]
- [ ] A note should be added that we are obviously only listing the projects that this community is involved in.
```

## SpaDES
Introduction about SpaDES modelling toolkit. 

```[tasklist]
- [ ] Point to resources on installation (external page; e.g. [here](https://github.com/PredictiveEcology/SpaDES/#readme)), getting started (external page; e.g. [here](https://github.com/PredictiveEcology/SpaDES/#readme)) and tutorials (internal page)
- [ ] get help: point to GitHub Issues ("each package/module/project has its own, so identify _where_ you need help") 
```

### Modules
List of all known SpaDES modules
Module list may be broken into "LandR" and "Other"

```[tasklist]
- [ ] Link to LandR (internal) page
```

### Packages
List and links to all SpaDES (and related) packages.

## LandR
A brief introduction of what LandR is, how it's striving to be PERFICT (using SpaDES as the toolkit)

```[tasklist]
- [ ] Link to manual 
- [ ] Point to publications
- [ ] Point to projects
```

## Training
Just a very brief introduction about the types of training offered (self-led -- link to tutorials; and presential -- point to workshops)

### Tutorials
A list of tutorials, each with a brief synopsis of what they are intended for and what level of SpaDES knowledge they require (if any).
Can go beyond "SpaDES" e.g. [reproducible workshops tutorial](https://ceresbarros.github.io/reproducible-workflowsWS/tutos_examples/reproducible-workflows-example/global.html)

### Workshops

```[tasklist]
- [ ] Point to [archived webpage of workshops prior to 2021](https://spades-workshops.predictiveecology.org/index.html)
```

## News
The list of news (blog)posts what is currently on the landing page

```[tasklist]
- [ ] Try to add it as lateral bar  of landing page.
```

## Publications
A list of publications using SpaDES/PERFICT from current collaborators only (?)

```[tasklist]
- [ ] Create a Zotero group for these publications and use it to make the list in the webpage
```

## Presentations
A list of presentations using SpaDES/PERFICT from current collaborators only (?)

```[tasklist]
- [ ] Create a Zotero group for these presentations and use it to make the list in the webpage
```

## Collaborators
We may still want to list people that are currently actively developing SpaDES modules?

# **TODO list**
```[tasklist]
### Clean README at [https://github.com/PredictiveEcology/SpaDES/](https://github.com/PredictiveEcology/SpaDES/)
- [ ] remove packages
- [ ] remove websites
- [ ] remove LandWeb or other projects
- [ ] remove workshops
- [ ] remove list of "reporting bugs" -- each package/module has their own.
- [ ] remove Q/A forum -- people will be directed to GH issues from now on.
- [ ] Queen -> King of England
- [ ] change text so that it's less focused on the package and more on the toolkit/approach.
```

```[tasklist]
### Tutorials
- [ ] Identify which tutorials will be adapted and re-used in current format and package versions
- [ ] find a way of archiving old tutorials somewhere (?)
- [ ] identify existing training materials that could be added to the list as tutorials (@achubaty may have some)
```

```[tasklist]
### old websites/resources
- [ ] spades.predictiveecology.org - add "archived note" and point to new predictiveecology.org/SpaDES
- [ ] spades-workshops.predictiveecology.org - add "archived note" and point to new predictiveecology.org/Workshops
- [ ] what to do about wiki?
```
