### ISSUE TITLE
List of TODOs

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/PredictiveEcology.org#25]
From meeting with @eliotmcintire 

**Both**
```[tasklist]
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/32
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/34
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/28
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/27
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/33
```

**Ceres**
```[tasklist]
### Tasks
- [x] add LandRDemo
- [x] on the Introduction chapter/SpaDES 101 sectionbreak, we wanted to add figures relating to modules and events + PERFICT figure
- [x] on Introduction we need a sentece that brings together R^3T, PERFICT, SpaDES and New Expectations
- [x] re order New Expectations, so that R^3T appears "together"
- [x] in the Preface: add that this book is (largely) about bringing together data+models to face the challenges/steps all ecology projects face (even if they skip some)
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/31
- [x] unnumber best practices
- [x] bad citation Sarma et al
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/26
- [x] use consistent capitalization in chapter/section titles
- [x] consistent use of .callout div appearance="simple"
- [ ] https://github.com/PredictiveEcology/PredictiveEcology.org/issues/29
- [x] automated building of R scripts
```

**Eliot**
```[tasklist]
### Tasks
- [x] Documentation -- as a topic -- the ways we write it, where to write it etc.
- [x] somewhere mention types of modules --
- [x] Add 3 visuals
- [x] `prepInputs`
- [x] `setupProject`
- [x] on spades workflows section break: figure/GIF with hexes
- [x] Found a Require bug -- seems fine -- unreproducible fail on Ian's computer
- [x] predictiveecology.r-universe.dev does not update packages.
- [x] reproducible
- [x] Continuous Workflow qmd
```

**Comment by CeresBarros** [comment]
"Both" task list moved to #35
