### ISSUE TITLE
PPTX of 2 sections (each)

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/PredictiveEcology.org#32]
```[tasklist]
### Tasks
- [x] Intro to SpaDES
- [x] Module files and metadata + inputs
- [x] simList
- [x] events and scheduling
- [x] continuous workflows + caching
- [x] prepInputs
- [x] workflows with setupProject
- [x] Cost of Flexibility, But it's worth it!
- [x] Add Ian's name to all pptx
```

**Comment by CeresBarros** [comment]
completed 7f8883b9d49c15d43b46098817232edab0957cc4
